// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: rzvR12HW4Cbga6buGGCB8Y
// Component: t0NTNgrAo1
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_graph.module.css"; // plasmic-import: rzvR12HW4Cbga6buGGCB8Y/projectcss
import sty from "./PlasmicPostsList.module.css"; // plasmic-import: t0NTNgrAo1/css

export type PlasmicPostsList__VariantMembers = {};

export type PlasmicPostsList__VariantsArgs = {};
type VariantPropType = keyof PlasmicPostsList__VariantsArgs;
export const PlasmicPostsList__VariantProps = new Array<VariantPropType>();

export type PlasmicPostsList__ArgsType = {};
type ArgPropType = keyof PlasmicPostsList__ArgsType;
export const PlasmicPostsList__ArgProps = new Array<ArgPropType>();

export type PlasmicPostsList__OverridesType = {
  root?: p.Flex<"div">;
  text?: p.Flex<"div">;
};

export interface DefaultPostsListProps {
  className?: string;
}

export const defaultPostsList__Args: Partial<PlasmicPostsList__ArgsType> = {};

function PlasmicPostsList__RenderFunc(props: {
  variants: PlasmicPostsList__VariantsArgs;
  args: PlasmicPostsList__ArgsType;
  overrides: PlasmicPostsList__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultPostsList__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Posts here"}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "text"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPostsList__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPostsList__VariantsArgs;
    args?: PlasmicPostsList__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPostsList__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPostsList__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPostsList__ArgProps,
      internalVariantPropNames: PlasmicPostsList__VariantProps
    });

    return PlasmicPostsList__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPostsList";
  } else {
    func.displayName = `PlasmicPostsList.${nodeName}`;
  }
  return func;
}

export const PlasmicPostsList = Object.assign(
  // Top-level PlasmicPostsList renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicPostsList
    internalVariantProps: PlasmicPostsList__VariantProps,
    internalArgProps: PlasmicPostsList__ArgProps
  }
);

export default PlasmicPostsList;
/* prettier-ignore-end */
